name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@master
        with:
          github_user_name: hashimhashmi02
          svg_out_path: dist/github-contribution-snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["dist/github-contribution-snake.svg"]'
          push: true
          new_branch: github-contribution-snake
